# Generated by Django 3.0.8 on 2020-07-25 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_data', '0002_plantingdata_seedling_batch_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='harvestdata',
            name='seedlingdata',
        ),
        migrations.RemoveField(
            model_name='seedlingwastagedata',
            name='seedlingdata',
        ),
        migrations.RemoveField(
            model_name='transplantdata',
            name='seedlingdata',
        ),
        migrations.RemoveField(
            model_name='wastagedata',
            name='seedlingdata',
        ),
        migrations.AddField(
            model_name='seedlingwastagedata',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Box'),
        ),
        migrations.AddField(
            model_name='seedlingwastagedata',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Rack'),
        ),
        migrations.AddField(
            model_name='seedlingwastagedata',
            name='square_meter_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Location'),
        ),
        migrations.AddField(
            model_name='harvestdata',
            name='seedling_batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Batch'),
        ),
        migrations.AddField(
            model_name='seedlingwastagedata',
            name='seedling_batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Batch'),
        ),
        migrations.AddField(
            model_name='transplantdata',
            name='seedling_batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Batch'),
        ),
        migrations.AddField(
            model_name='wastagedata',
            name='seedling_batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Batch'),
        ),
        migrations.AlterField(
            model_name='plantingdata',
            name='seedling_batch_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.Batch'),
        ),
    ]
