# Generated by Django 3.0.8 on 2020-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_data', '0003_auto_20200725_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='num',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
