# Generated by Django 3.0.8 on 2020-07-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_data', '0005_auto_20200725_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestdata',
            name='no_of_heads',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
