# Generated by Django 3.0.8 on 2020-07-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_data', '0006_auto_20200725_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producetype',
            name='seed_brand',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producetype',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
