# Generated by Django 3.0.8 on 2020-08-11 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydro_data', '0007_auto_20200725_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.CharField(max_length=100)),
                ('order_no', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mop', models.CharField(max_length=100)),
                ('delivery_fee', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('discount_code', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100)),
                ('products', models.CharField(max_length=100)),
                ('prod_weight', models.FloatField()),
                ('prod_qty', models.CharField(max_length=100)),
                ('prod_price', models.CharField(max_length=100)),
                ('order_sum', models.CharField(max_length=500)),
                ('total_weight', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PackagedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeightCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_packs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Packs')),
                ('packaged_by', models.ManyToManyField(blank=True, to='hydro_data.PackagedBy')),
                ('prod_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='names', to='hydro_data.ProductName')),
            ],
        ),
        migrations.CreateModel(
            name='PackingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('date_harvested', models.DateField(null=True, verbose_name='Date Harvested')),
                ('date_packaged', models.DateField(null=True, verbose_name='Date Packaged')),
                ('no_of_packs', models.PositiveIntegerField(null=True, verbose_name='Number of Packs')),
                ('custom_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydro_data.CustomerName', verbose_name='Customer Name')),
                ('packaged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydro_data.PackagedBy', verbose_name='Packaged By')),
                ('prod_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hydro_data.ProductName', verbose_name='Product Name')),
            ],
        ),
    ]
