from django.contrib import admin
from .models import CustomerName, ProductName, PackagedBy, DeliveryData, CustomerType, PackingLog, WeightCategory, Site,Box,WaterConsumption,EnergyConsumption,GrowMedium,Tray,Device,DeviceCalibration,Rack,BoxRack,ProduceType,Location,RackLocation,Acid,Nutrient,Activity,Tank,Batch,PlantingData,TransplantData,SeedlingWastageData,HarvestData,WastageData,SpoilageData,LightReading,AirReading,WaterReading

# Register your models here.
admin.site.register(Site)
admin.site.register(WaterConsumption)
admin.site.register(EnergyConsumption)
admin.site.register(Box)
admin.site.register(Rack)
admin.site.register(BoxRack)
admin.site.register(ProduceType)
admin.site.register(Location)
admin.site.register(RackLocation)
admin.site.register(Acid)
admin.site.register(Nutrient)
admin.site.register(Activity)
admin.site.register(GrowMedium)
admin.site.register(Tray)
admin.site.register(Tank)
admin.site.register(Device)
admin.site.register(DeviceCalibration)
admin.site.register(Batch)
admin.site.register(PlantingData)
admin.site.register(TransplantData)
admin.site.register(SeedlingWastageData)
admin.site.register(WastageData)
admin.site.register(SpoilageData)
admin.site.register(HarvestData)
admin.site.register(LightReading)
admin.site.register(AirReading)
admin.site.register(WaterReading)
admin.site.register(WeightCategory)
admin.site.register(PackingLog)
admin.site.register(CustomerType)
admin.site.register(DeliveryData)
admin.site.register(PackagedBy)
admin.site.register(ProductName)
admin.site.register(CustomerName)